version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run Tests
          command: mvn clean test
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build